// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// cpp_cbc_solve.cpp
writable::list cpp_cbc_solve(doubles obj, bool isMaximization, integers rowIndices, integers colIndices, doubles elements, integers integerIndices, doubles colLower, doubles colUpper, doubles rowLower, doubles rowUpper, strings arguments, integers initialIndex, doubles initialSolution, strings initialNames, bool useInitialSolution);
extern "C" SEXP _rcbc_cpp_cbc_solve(SEXP obj, SEXP isMaximization, SEXP rowIndices, SEXP colIndices, SEXP elements, SEXP integerIndices, SEXP colLower, SEXP colUpper, SEXP rowLower, SEXP rowUpper, SEXP arguments, SEXP initialIndex, SEXP initialSolution, SEXP initialNames, SEXP useInitialSolution) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_cbc_solve(cpp11::as_cpp<cpp11::decay_t<doubles>>(obj), cpp11::as_cpp<cpp11::decay_t<bool>>(isMaximization), cpp11::as_cpp<cpp11::decay_t<integers>>(rowIndices), cpp11::as_cpp<cpp11::decay_t<integers>>(colIndices), cpp11::as_cpp<cpp11::decay_t<doubles>>(elements), cpp11::as_cpp<cpp11::decay_t<integers>>(integerIndices), cpp11::as_cpp<cpp11::decay_t<doubles>>(colLower), cpp11::as_cpp<cpp11::decay_t<doubles>>(colUpper), cpp11::as_cpp<cpp11::decay_t<doubles>>(rowLower), cpp11::as_cpp<cpp11::decay_t<doubles>>(rowUpper), cpp11::as_cpp<cpp11::decay_t<strings>>(arguments), cpp11::as_cpp<cpp11::decay_t<integers>>(initialIndex), cpp11::as_cpp<cpp11::decay_t<doubles>>(initialSolution), cpp11::as_cpp<cpp11::decay_t<strings>>(initialNames), cpp11::as_cpp<cpp11::decay_t<bool>>(useInitialSolution)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_rcbc_cpp_cbc_solve", (DL_FUNC) &_rcbc_cpp_cbc_solve, 15},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_rcbc(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
