# Generated by cpp11: do not edit by hand

cpp_cbc_solve <- function(obj, isMaximization, rowIndices, colIndices, elements, integerIndices, colLower, colUpper, rowLower, rowUpper, arguments, initialIndex, initialSolution, initialNames, useInitialSolution) {
  .Call(`_rcbc_cpp_cbc_solve`, obj, isMaximization, rowIndices, colIndices, elements, integerIndices, colLower, colUpper, rowLower, rowUpper, arguments, initialIndex, initialSolution, initialNames, useInitialSolution)
}
